server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          # ✅ Gateway télécharge la clé publique depuis auth-service
          jwk-set-uri: http://localhost:8081/oauth2/jwks

  cloud:
    gateway:
      routes:
        # ✅ PUBLIC — pas de sécurité
        - id: auth-login
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
            
        - id: auth-login-user
          uri: lb://auth-service
          predicates:
            - Path=/api/users/**
              
        
        # ✅ PROTÉGÉ — JWT validé automatiquement
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**

        - id: production-service
          uri: lb://production-service
          predicates:
            - Path=/api/production/**

        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/invoices/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka